# Generated by Django 2.2.13 on 2020-11-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='legal_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
